import io
from weasyprint import HTML


def generate_qa_pdf(question: str, answer: str, sources: list) -> bytes:
    sources_html = ""
    for s in sources:
        sources_html += f"""
        <div class="source">
            <strong>{s['filename']} — chunk {s['chunk_index']}</strong>
            <p>{s['excerpt']}</p>
        </div>
        """

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{ font-family: Arial, sans-serif; padding: 40px; color: #333; }}
            h1 {{ color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 10px; }}
            h2 {{ color: #16213e; margin-top: 30px; }}
            .question {{ background: #f0f4ff; padding: 15px; border-left: 4px solid #4a6fa5; border-radius: 4px; }}
            .answer {{ background: #f9f9f9; padding: 15px; border-left: 4px solid #28a745; border-radius: 4px; }}
            .source {{ background: #fff8e1; padding: 10px; margin: 10px 0; border-radius: 4px; border: 1px solid #ffe082; }}
            .source p {{ font-size: 12px; color: #555; margin: 5px 0 0 0; }}
            .footer {{ margin-top: 40px; font-size: 11px; color: #999; text-align: center; }}
        </style>
    </head>
    <body>
        <h1>DocMind — Q&A Report</h1>

        <h2>Question</h2>
        <div class="question"><p>{question}</p></div>

        <h2>Answer</h2>
        <div class="answer"><p>{answer}</p></div>

        <h2>Sources</h2>
        {sources_html}

        <div class="footer">Generated by DocMind</div>
    </body>
    </html>
    """

    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes